# mlops-experiments/argocd/manifests/monitoring-extras/prometheus.yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-main
  namespace: monitoring
spec:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  serviceMonitorSelector: {}         # підхоплювати всі ServiceMonitor у ns
  podMonitorSelector: {}             # і всі PodMonitor
  retention: 12h
  enableAdminAPI: false
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-main
  namespace: monitoring
  labels:
    app: prometheus
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9090
      targetPort: web
  selector:
    prometheus: prometheus-main      # так оператор лейблить pod'и Prometheus
