apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pushgateway
  namespace: monitoring
  labels:
    # щоб ArgoCD керував цим маніфестом (як і раніше)
    argocd.argoproj.io/instance: monitoring-extras
    # ГОЛОВНЕ: ця мітка має збігатися з селектором у Prometheus
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/instance: pushgateway
      app.kubernetes.io/name: prometheus-pushgateway
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
