stages:
  - train

variables:
  AWS_DEFAULT_REGION: "eu-central-1"

train-model:
  stage: train
  image: amazon/aws-cli:2.15.0
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
  script:
    - aws --version
    - aws stepfunctions start-execution --region "$AWS_DEFAULT_REGION" --state-machine-arn "$SFN_ARN" --name "train-$(date +%s)" --input "{\"source\":\"gitlab-ci\",\"commit\":\"$CI_COMMIT_SHORT_SHA\"}"
