apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: infra-tools
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  source:
    chart: oci://registry-1.docker.io/bitnamicharts/minio
    targetRevision: ">=0.0.0"          # можна залишити діапазон; або постав конкретну версію
    helm:
      parameters:
        - name: fullnameOverride
          value: minio
        - name: replicas
          value: "1"
        - name: service.type
          value: ClusterIP
        - name: buckets[0].name
          value: mlflow-artifacts
        - name: buckets[0].forceCreate
          value: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
