apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-secrets
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://github.com/<ТВІЙ_ЮЗЕР>/<ТВІЙ_РЕПОЗИТОРІЙ>.git
    targetRevision: lesson-8-9
    path: mlops-experiments/argocd/manifests/secrets
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
