apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: infra-tools
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "*"           # остання стабільна версія
    helm:
      values: |
        grafana:
          adminUser: admin
          adminPassword: admin              # для демо; за бажанням винеси у Secret
          service:
            type: ClusterIP
        prometheus:
          service:
            type: ClusterIP
          prometheusSpec:
            # дозволь підхоплювати ServiceMonitor/PodMonitor з будь-якими лейблами
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
