apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: "*"
    helm:
      parameters:
        - name: fullnameOverride
          value: "postgres"
        - name: auth.username
          value: "mlflow"
        - name: auth.password
          value: "mlflow123"
        - name: auth.database
          value: "mlflow"
        - name: primary.service.type
          value: "ClusterIP"
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
