apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: infra-tools
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  source:
    chart: oci://registry-1.docker.io/bitnamicharts/postgresql
    targetRevision: ">=0.0.0"          # або зафіксуй конкретну версію
    helm:
      parameters:
        - name: fullnameOverride
          value: postgres
        - name: auth.username
          value: mlflow
        - name: auth.password
          value: mlflow123
        - name: auth.database
          value: mlflow
        - name: primary.service.type
          value: ClusterIP
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
