apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pushgateway
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames: ["monitoring"]
  selector:
    matchLabels:
      app.kubernetes.io/name: pushgateway   # дивись, щоб збігався з labels сервісу
  endpoints:
    - port: http      # ім'я порту в Service pushgateway (у більшості чартів так і є)
      path: /metrics
      interval: 15s
