# Базові налаштування сервісів і таймаутів для чарту Argo CD
global:
  image:
    tag: ""  # застосовується дефолт з чарту

configs:
  params:
    # приклад додаткових аргументів для контролера синків
    server.insecure: "true"  # для простого демо (UI без TLS за кластером)
  cm:
    timeout.reconciliation: "60s"  # як часто ArgoCD синкає

server:
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080
  extraArgs:
    - --insecure
  # RBAC приклад (можна розширити під себе)
  rbacConfig:
    create: true
  # Ресурси за потреби
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

controller:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

repoServer:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

applicationSet:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
