apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:latest  # або офіційний python:3.9 + pip install mlflow
          args:
            - mlflow
            - server
            - --backend-store-uri=$(BACKEND_STORE_URI)
            - --default-artifact-root=$(ARTIFACT_ROOT)
            - --host=0.0.0.0
            - --port=5000
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: mlflow-config
