apiVersion: v1
kind: Service
metadata:
  name: mlflow
  labels:
    app: mlflow
spec:
  type: ClusterIP
  selector:
    app: mlflow            # має збігатися з labels у pod (template.metadata.labels)
  ports:
    - name: http
      port: 5000
      targetPort: 5000
